---
- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present
  tags: install

- name: Ensure web root exists
  ansible.builtin.file:
    path: "{{ nginx_site_root }}"
    state: directory
    mode: '0755'

- name: Deploy index.html from template
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ nginx_site_root }}/index.html"
    mode: '0644'
  notify: restart nginx
  diff: yes
  tags: config

- name: Configure Nginx site
  ansible.builtin.copy:
    dest: "{{ nginx_conf_path }}"
    content: |
      server {
          listen {{ websvc_port }};
          server_name _;
          root {{ nginx_site_root }};
          index index.html;
      }
  notify: restart nginx
  diff: yes
  tags: config

- name: Open firewall port (firewalld)
  ansible.posix.firewalld:
    port: "{{ websvc_port }}/tcp"
    permanent: yes
    state: enabled
    immediate: yes
  when: ansible_facts.os_family == "RedHat"
  tags: firewall

- name: Open firewall port (ufw)
  community.general.ufw:
    rule: allow
    port: "{{ websvc_port }}"
    proto: tcp
  when: ansible_facts.os_family == "Debian"
  tags: firewall

