---
- name: Install IIS Web Server
  ansible.windows.win_feature:
    name:
      - Web-Server
      - Web-WebServer
      - Web-Mgmt-Tools
      - Web-Mgmt-Console
    state: present
    include_management_tools: yes
  async: 600
  poll: 5
  register: iis_install
  tags: setup

- name: Reboot if IIS install required
  ansible.windows.win_reboot:
  when: iis_install.reboot_required
  tags: setup

- name: Ensure IIS application pool exists
  community.windows.win_iis_webapppool:
    name: "{{ iis_pool_name }}"
    state: started
  tags: config

- name: Configure IIS app pool identity
  community.windows.win_iis_webapppool:
    name: "{{ iis_pool_name }}"
    state: started
    identity: specificUser
    username: "{{ iis_pool_user }}"
    password: "{{ iis_pool_password }}"
      #no_log: true
  tags: config

- name: Ensure IIS site exists
  community.windows.win_iis_website:
    name: "{{ iis_site_name }}"
    state: started
    port: "{{ websvc_port }}"
    ip: "*"
    hostname: ""
    physical_path: "{{ iis_site_path }}"
    application_pool: "{{ iis_pool_name }}"
  tags: config

- name: Allow HTTP port in Windows Firewall
  community.windows.win_firewall_rule:
    name: "Allow HTTP on port {{ websvc_port }}"
    localport: "{{ websvc_port }}"
    action: allow
    direction: in
    protocol: TCP
    state: present
    enabled: yes
  tags: firewall

